version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
      - "mysql"
    ports:
      - '4466:4466'
    environment:
      PRISMA_ENDPOINT: http://prisma:4466
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  prisma_init:
    build: ./backend/prisma_config
    image: speedcar/prisma_init:v1
    depends_on:
      - "prisma"
    command: ["./wait_for_it.sh", "prisma:4466", "--", "prisma", "deploy"]
  backend:
    build: ./backend
    image: speedcar/backend:v1
    restart: always
    ports:
      - "4000:4000"
    depends_on:
        - "prisma"
        - "prisma_init"
  frontend:
    build: ./frontend
    image: speedcar/frontend:v1
    restart: always
    ports:
      - "3000:3000"
    depends_on:
        - "backend"
volumes:
  mysql: ~
